#### Sensors.yaml ####
- platform: yr
- platform: mqtt
  name: 'temperature_cuisine'
  state_topic: "sensors/dht/1/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: 'humidity_cuisine'
  state_topic: "sensors/dht/1/humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: 'temperature_chambre'
  state_topic: "sensors/sht30/1/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: 'humidity_chambre'
  state_topic: "sensors/sht30/1/humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: 'temperature_salon'
  state_topic: "sensors/sht30/2/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: 'humidity_salon'
  state_topic: "sensors/sht30/1/humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: 'temperature_sejour'
  state_topic: "sensors/dht/2/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: 'humidity_sejour'
  state_topic: "sensors/dht/2/humidity"
  unit_of_measurement: "%"

- platform: mqtt
  name: 'temperature_flottant'
  state_topic: "sensors/dht/3/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  name: 'humidity_flottant'
  state_topic: "sensors/dht/3/humidity"
  unit_of_measurement: "%"


- platform: darksky
  api_key: 6d80c66076dbcbc6e18c5cd5b2c9cdcb
  monitored_conditions:
      - summary
      - daily_summary
      - hourly_summary
      - icon
      - temperature
      - apparent_temperature
      - temperature_max
      - temperature_min
      - precip_intensity
      - precip_probability
      - humidity
      - pressure
      - visibility
      - ozone
      - wind_speed
      - wind_bearing


- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  minute: 
    - 0
    - 1
    - 2 
    - 3 
    - 4 
    - 6 
    - 7 
    - 8 
    - 9
    - 5
    - 10
    - 11
    - 12 
    - 13 
    - 14 
    - 16 
    - 17 
    - 18 
    - 19
    - 15
    - 20
    - 21
    - 22 
    - 23 
    - 24 
    - 26 
    - 27 
    - 28 
    - 29
    - 25
    - 30
    - 31
    - 32 
    - 33 
    - 34 
    - 36 
    - 37 
    - 38 
    - 39
    - 35
    - 40
    - 45
    - 41
    - 42 
    - 43 
    - 44 
    - 46 
    - 47 
    - 48 
    - 49
    - 50
    - 51
    - 52 
    - 53 
    - 54 
    - 56 
    - 57 
    - 58 
    - 59
    - 55 
